{ config, pkgs, lib, hyprScripts, ... }:

let
  scheduledThemeNames = [
    "neobrutalist"
    "neobrutalist-light"
  ];

  runtimeThemeNames = config.theme.available;
  scheduledThemeEnabled = lib.elem config.theme.name scheduledThemeNames;
  initialThemeCommand = if scheduledThemeEnabled then "auto" else config.theme.name;

  runtimeThemes = lib.genAttrs runtimeThemeNames (themeName:
    config.theme.definitions.${themeName}
  );

  vscodeTheme = import ../lib/vscode-theme.nix { };

  stripHash = color: builtins.substring 1 6 color;
  boolString = value: if value then "true" else "false";
  modeFor = theme: if theme.appearance.preferDark then "dark" else "light";
  gtkColorSchemeFor = theme:
    if theme.appearance.preferDark then "prefer-dark" else "prefer-light";

  hyprColor = color: "0xFF${stripHash color}";
  # Shared by Ghostty and Alacritty so both terminals render identically.
  terminalBackground = theme:
    if theme.appearance.preferDark then theme.colors.background else "#e6dfd5";
  # Theme selection colors are dark enough to stay visible on the light
  # terminal background (#e6dfd5), so no light-mode override is needed.
  terminalSelectionBackground = theme: theme.colors.selection;

  colorsShell = themeName: theme: ''
    # Generated by Home Manager. Runtime consumers source this file.
    THEME_NAME="${themeName}"
    THEME_DISPLAY_NAME="${theme.name}"
    THEME_MODE="${modeFor theme}"
    GTK_COLOR_SCHEME="${gtkColorSchemeFor theme}"
    GTK_THEME="${theme.appearance.gtkTheme}"
    ICON_THEME="${theme.appearance.iconTheme}"
    CURSOR_THEME="${theme.appearance.cursorTheme}"
    CURSOR_SIZE="${toString theme.appearance.cursorSize}"
    KVANTUM_THEME="${theme.appearance.kvantumTheme}"
    PREFER_DARK="${boolString theme.appearance.preferDark}"

    C_BG="${theme.colors.background}"
    C_BG_ALT="${theme.colors.backgroundAlt}"
    C_SURFACE="${theme.colors.surface}"
    C_FG="${theme.colors.foreground}"
    C_DIM="${theme.colors.foregroundDim}"
    C_MUTED="${theme.colors.comment}"
    C_ACCENT="${theme.colors.accent}"
    C_ACCENT_SECONDARY="${theme.colors.accentSecondary}"
    C_RED="${theme.colors.red}"
    C_ORANGE="${theme.colors.orange}"
    C_YELLOW="${theme.colors.yellow}"
    C_GREEN="${theme.colors.green}"
    C_CYAN="${theme.colors.cyan}"
    C_BLUE="${theme.colors.blue}"
    C_MAGENTA="${theme.colors.magenta}"
    C_BORDER="${theme.colors.border}"
    C_SELECTION="${theme.colors.selection}"
    C_BRIGHT_BLACK="${theme.colors.brightBlack}"
    C_BRIGHT_WHITE="${theme.colors.brightWhite}"
    C_TERM_BG="${terminalBackground theme}"
    C_TERM_SELECTION="${terminalSelectionBackground theme}"
  '';

  waybarCss = theme: ''
    /* Generated runtime colors. Imported by ~/.config/waybar/style.css. */
    @define-color bg ${theme.colors.background};
    @define-color bg_alt ${theme.colors.backgroundAlt};
    @define-color surface ${theme.colors.surface};
    @define-color fg ${theme.colors.foreground};
    @define-color dim ${theme.colors.foregroundDim};
    @define-color muted ${theme.colors.comment};
    @define-color accent ${theme.colors.accent};
    @define-color accent_secondary ${theme.colors.accentSecondary};
    @define-color red ${theme.colors.red};
    @define-color green ${theme.colors.green};
    @define-color blue ${theme.colors.blue};
    @define-color orange ${theme.colors.orange};
    @define-color cyan ${theme.colors.cyan};
    @define-color magenta ${theme.colors.magenta};
    @define-color border_color ${theme.colors.border};
    @define-color selection ${theme.colors.selection};
  '';

  hyprLua = theme: ''
    return {
      mode = "${modeFor theme}",
      prefer_dark = ${boolString theme.appearance.preferDark},
      colors = {
        background = "${stripHash theme.colors.background}",
        backgroundAlt = "${stripHash theme.colors.backgroundAlt}",
        surface = "${stripHash theme.colors.surface}",
        foreground = "${stripHash theme.colors.foreground}",
        foregroundDim = "${stripHash theme.colors.foregroundDim}",
        accent = "${stripHash theme.colors.accent}",
        accentSecondary = "${stripHash theme.colors.accentSecondary}",
        border = "${stripHash theme.colors.border}",
        comment = "${stripHash theme.colors.comment}",
      },
    }
  '';

  ghosttyConf = theme: ''
    # Generated runtime colors. Included from the main Ghostty config.
    background = ${terminalBackground theme}
    foreground = ${theme.colors.foreground}
    selection-background = ${terminalSelectionBackground theme}
    selection-foreground = ${theme.colors.foreground}
    cursor-color = ${theme.colors.accent}

    palette = 0=${theme.colors.brightBlack}
    palette = 1=${theme.colors.red}
    palette = 2=${theme.colors.green}
    palette = 3=${theme.colors.yellow}
    palette = 4=${theme.colors.blue}
    palette = 5=${theme.colors.magenta}
    palette = 6=${theme.colors.cyan}
    palette = 7=${theme.colors.foreground}
    palette = 8=${theme.colors.comment}
    palette = 9=${theme.colors.red}
    palette = 10=${theme.colors.green}
    palette = 11=${theme.colors.yellow}
    palette = 12=${theme.colors.blue}
    palette = 13=${theme.colors.magenta}
    palette = 14=${theme.colors.cyan}
    palette = 15=${theme.colors.brightWhite}
  '';

  alacrittyToml = theme: ''
    # Generated runtime colors. Imported by Alacritty when available.
    [colors.primary]
    background = "${terminalBackground theme}"
    foreground = "${theme.colors.foreground}"

    [colors.cursor]
    text = "${terminalBackground theme}"
    cursor = "${theme.colors.accent}"

    [colors.selection]
    text = "${theme.colors.foreground}"
    background = "${terminalSelectionBackground theme}"

    [colors.search.matches]
    foreground = "${theme.colors.background}"
    background = "${theme.colors.yellow}"

    [colors.search.focused_match]
    foreground = "${theme.colors.background}"
    background = "${theme.colors.accent}"

    [colors.hints.start]
    foreground = "${theme.colors.background}"
    background = "${theme.colors.accent}"

    [colors.hints.end]
    foreground = "${theme.colors.background}"
    background = "${theme.colors.yellow}"

    [colors.footer_bar]
    foreground = "${theme.colors.foreground}"
    background = "${theme.colors.backgroundAlt}"

    [colors.line_indicator]
    foreground = "${theme.colors.accent}"
    background = "${theme.colors.backgroundAlt}"

    [colors.vi_mode_cursor]
    text = "${terminalBackground theme}"
    cursor = "${theme.colors.accent}"

    [colors.normal]
    black = "${theme.colors.brightBlack}"
    red = "${theme.colors.red}"
    green = "${theme.colors.green}"
    yellow = "${theme.colors.yellow}"
    blue = "${theme.colors.blue}"
    magenta = "${theme.colors.magenta}"
    cyan = "${theme.colors.cyan}"
    white = "${theme.colors.foreground}"

    [colors.bright]
    black = "${theme.colors.comment}"
    red = "${theme.colors.red}"
    green = "${theme.colors.green}"
    yellow = "${theme.colors.yellow}"
    blue = "${theme.colors.blue}"
    magenta = "${theme.colors.magenta}"
    cyan = "${theme.colors.cyan}"
    white = "${theme.colors.brightWhite}"
  '';

  makoConf = theme: ''
    background-color=${theme.colors.backgroundAlt}
    text-color=${theme.colors.foreground}
    border-color=${theme.colors.accent}
    progress-color=over ${theme.colors.surface}
    border-radius=6
    border-size=2
    width=360
    height=150
    max-visible=3
    margin=8
    padding=14
    default-timeout=4000
    ignore-timeout=false
    font=${theme.fonts.mono} 10
    icons=true
    max-icon-size=32
    icon-location=left
    actions=true
    group-by=app-name
    format=<b>%s</b>\n%b
    layer=overlay
    anchor=top-right

    [urgency=low]
    default-timeout=2000
    border-color=${theme.colors.border}

    [urgency=high]
    border-color=${theme.colors.red}
    default-timeout=0

    [app-name=SwayOSD]
    default-timeout=1000
    group-by=app-name
  '';

  swayosdCss = theme: ''
    window {
      background: ${theme.colors.backgroundAlt};
      border-radius: 8px;
      border: 1px solid ${theme.colors.surface};
      padding: 14px;
    }

    #container {
      margin: 6px;
    }

    progressbar {
      min-height: 6px;
      border-radius: 3px;
      background: transparent;
    }

    trough {
      min-height: 6px;
      border-radius: 3px;
      background: ${theme.colors.surface};
    }

    progress {
      min-height: 6px;
      border-radius: 3px;
      background: ${theme.colors.accent};
    }

    label {
      font-family: "${theme.fonts.mono}";
      font-size: 12px;
      color: ${theme.colors.foreground};
      margin: 4px;
    }

    image {
      color: ${theme.colors.foreground};
    }
  '';

  wofiCss = theme: ''
    * {
      font-family: "${theme.fonts.mono}", monospace;
      font-size: 12px;
    }

    window {
      margin: 0;
      padding: 0;
      background-color: ${theme.colors.backgroundAlt};
      border: 1px solid ${theme.colors.border};
      border-radius: 8px;
      color: ${theme.colors.foreground};
    }

    #outer-box {
      margin: 0;
      padding: 10px;
      background-color: ${theme.colors.backgroundAlt};
    }

    #input {
      margin: 0 0 8px 0;
      padding: 8px 10px;
      background-color: ${theme.colors.surface};
      border: 1px solid ${theme.colors.border};
      border-radius: 6px;
      color: ${theme.colors.foreground};
    }

    #input:focus {
      border-color: ${theme.colors.accent};
    }

    #scroll {
      margin: 0;
      border: none;
    }

    #inner-box {
      margin: 0;
      padding: 0;
      background-color: transparent;
    }

    #entry {
      padding: 8px 10px;
      border-radius: 6px;
      color: ${theme.colors.foregroundDim};
    }

    #entry:selected {
      background-color: ${theme.colors.selection};
      color: ${theme.colors.foreground};
    }

    #text {
      color: inherit;
    }

    #img {
      margin-right: 8px;
    }
  '';

  nemoCss = theme: ''
    /* Nemo - runtime themed sharp, minimal file manager. */

    .nemo-window,
    .nemo-window .sidebar,
    .nemo-window .view,
    .nemo-window button,
    .nemo-window entry,
    .nemo-window .path-bar button {
      border-radius: 0;
    }

    .nemo-window {
      background-color: ${theme.colors.background};
      color: ${theme.colors.foreground};
    }

    .nemo-window .sidebar {
      background-color: ${theme.colors.backgroundAlt};
      color: ${theme.colors.foreground};
      border-right: 1px solid ${theme.colors.border};
    }

    .nemo-window .sidebar row {
      padding: 4px 8px;
      border-radius: 0;
      color: ${theme.colors.foreground};
    }

    .nemo-window .sidebar row:selected,
    .nemo-window .sidebar row:selected label {
      background-color: ${theme.colors.selection};
      color: ${theme.colors.foreground};
    }

    .nemo-window .sidebar row:hover {
      background-color: ${theme.colors.surface};
    }

    .nemo-window .view,
    .nemo-window iconview,
    .nemo-window treeview.view {
      background-color: ${theme.colors.background};
      color: ${theme.colors.foreground};
    }

    .nemo-window .view:selected,
    .nemo-window iconview:selected,
    .nemo-window treeview.view:selected {
      background-color: ${theme.colors.selection};
      color: ${theme.colors.foreground};
    }

    .nemo-window .view:hover,
    .nemo-window iconview:hover,
    .nemo-window treeview.view:hover {
      background-color: ${theme.colors.backgroundAlt};
    }

    .nemo-window treeview.view {
      -GtkTreeView-horizontal-separator: 8;
      -GtkTreeView-vertical-separator: 3;
    }

    .nemo-window .path-bar button {
      background: transparent;
      border: none;
      padding: 4px 8px;
      color: ${theme.colors.foreground};
    }

    .nemo-window .path-bar button:hover {
      background-color: ${theme.colors.surface};
    }

    .nemo-window toolbar,
    .nemo-window headerbar {
      background-color: ${theme.colors.backgroundAlt};
      color: ${theme.colors.foreground};
      border-bottom: 1px solid ${theme.colors.border};
      padding: 2px;
    }

    .nemo-window toolbar button,
    .nemo-window headerbar button {
      background: transparent;
      border: none;
      color: ${theme.colors.foreground};
      padding: 6px;
      border-radius: 0;
    }

    .nemo-window toolbar button:hover,
    .nemo-window headerbar button:hover {
      background-color: ${theme.colors.surface};
    }

    .nemo-window popover,
    .nemo-window menu {
      background-color: ${theme.colors.surface};
      color: ${theme.colors.foreground};
      border: 1px solid ${theme.colors.border};
    }

    .nemo-window menuitem:hover {
      background-color: ${theme.colors.selection};
    }

    .nemo-window statusbar {
      background-color: ${theme.colors.backgroundAlt};
      border-top: 1px solid ${theme.colors.border};
      padding: 2px 8px;
      font-size: 0.9em;
      color: ${theme.colors.foregroundDim};
    }

    .nemo-window scrollbar {
      background-color: transparent;
    }

    .nemo-window scrollbar slider {
      background-color: ${theme.colors.border};
      border-radius: 0;
      min-width: 6px;
      min-height: 6px;
    }

    .nemo-window scrollbar slider:hover {
      background-color: ${theme.colors.foregroundDim};
    }
  '';

  hyprtoolkitConf = theme: ''
    background = ${hyprColor theme.colors.background}
    base = ${hyprColor theme.colors.background}
    alternate_base = ${hyprColor theme.colors.surface}

    text = ${hyprColor theme.colors.foreground}
    bright_text = ${hyprColor theme.colors.brightWhite}

    accent = ${hyprColor theme.colors.accent}
    accent_secondary = ${hyprColor theme.colors.accentSecondary}

    font_size = 12
    h1_size = 17
    h2_size = 14
    h3_size = 12
    small_font_size = 10
    icon_theme = hicolor
  '';

  btopTheme = theme: ''
    theme[main_bg]="${theme.colors.background}"
    theme[main_fg]="${theme.colors.foreground}"
    theme[title]="${theme.colors.foreground}"
    theme[hi_fg]="${theme.colors.accent}"
    theme[selected_bg]="${theme.colors.selection}"
    theme[selected_fg]="${theme.colors.accent}"
    theme[inactive_fg]="${theme.colors.comment}"
    theme[graph_text]="${theme.colors.foreground}"
    theme[meter_bg]="${theme.colors.surface}"
    theme[proc_misc]="${theme.colors.cyan}"

    theme[cpu_box]="${theme.colors.border}"
    theme[mem_box]="${theme.colors.border}"
    theme[net_box]="${theme.colors.border}"
    theme[proc_box]="${theme.colors.border}"
    theme[div_line]="${theme.colors.comment}"

    theme[temp_start]="${theme.colors.cyan}"
    theme[temp_mid]="${theme.colors.yellow}"
    theme[temp_end]="${theme.colors.red}"

    theme[cpu_start]="${theme.colors.green}"
    theme[cpu_mid]="${theme.colors.yellow}"
    theme[cpu_end]="${theme.colors.red}"

    theme[free_start]="${theme.colors.comment}"
    theme[free_mid]="${theme.colors.cyan}"
    theme[free_end]="${theme.colors.green}"

    theme[cached_start]="${theme.colors.comment}"
    theme[cached_mid]="${theme.colors.yellow}"
    theme[cached_end]="${theme.colors.orange}"

    theme[available_start]="${theme.colors.comment}"
    theme[available_mid]="${theme.colors.green}"
    theme[available_end]="${theme.colors.cyan}"

    theme[used_start]="${theme.colors.green}"
    theme[used_mid]="${theme.colors.yellow}"
    theme[used_end]="${theme.colors.red}"

    theme[download_start]="${theme.colors.cyan}"
    theme[download_mid]="${theme.colors.magenta}"
    theme[download_end]="${theme.colors.red}"

    theme[upload_start]="${theme.colors.green}"
    theme[upload_mid]="${theme.colors.yellow}"
    theme[upload_end]="${theme.colors.red}"

    theme[process_start]="${theme.colors.cyan}"
    theme[process_mid]="${theme.colors.yellow}"
    theme[process_end]="${theme.colors.red}"
  '';

  kvantumConfig = theme: ''
    [General]
    theme=${theme.appearance.kvantumTheme}
  '';

  gtkSettingsIni = theme: ''
    [Settings]
    gtk-application-prefer-dark-theme=${boolString theme.appearance.preferDark}
    gtk-cursor-theme-name=${theme.appearance.cursorTheme}
    gtk-cursor-theme-size=${toString theme.appearance.cursorSize}
    gtk-decoration-layout=menu:
    gtk-enable-animations=true
    gtk-font-name=${theme.fonts.sans} ${toString theme.fonts.sansSize}
    gtk-icon-theme-name=${theme.appearance.iconTheme}
    gtk-theme-name=${theme.appearance.gtkTheme}
  '';

  gtk2Rc = theme: ''
    gtk-application-prefer-dark-theme=${boolString theme.appearance.preferDark}
    gtk-cursor-theme-name="${theme.appearance.cursorTheme}"
    gtk-cursor-theme-size=${toString theme.appearance.cursorSize}
    gtk-font-name="${theme.fonts.sans} ${toString theme.fonts.sansSize}"
    gtk-icon-theme-name="${theme.appearance.iconTheme}"
    gtk-theme-name="${theme.appearance.gtkTheme}"
  '';

  themeAssets = lib.foldl'
    (acc: themeName:
      let
        theme = runtimeThemes.${themeName};
      in
      acc // {
        "theme/themes/${themeName}/colors.sh".text = colorsShell themeName theme;
        "theme/themes/${themeName}/waybar.css".text = waybarCss theme;
        "theme/themes/${themeName}/hypr.lua".text = hyprLua theme;
        "theme/themes/${themeName}/ghostty.conf".text = ghosttyConf theme;
        "theme/themes/${themeName}/alacritty.toml".text = alacrittyToml theme;
        "theme/themes/${themeName}/mako.conf".text = makoConf theme;
        "theme/themes/${themeName}/swayosd.css".text = swayosdCss theme;
        "theme/themes/${themeName}/wofi.css".text = wofiCss theme;
        "theme/themes/${themeName}/nemo.css".text = nemoCss theme;
        "theme/themes/${themeName}/vscode-settings.json".text =
          builtins.toJSON (vscodeTheme.settingsFor theme);
        "theme/themes/${themeName}/hyprtoolkit.conf".text = hyprtoolkitConf theme;
        "theme/themes/${themeName}/btop.theme".text = btopTheme theme;
        "theme/themes/${themeName}/kvantum.kvconfig".text = kvantumConfig theme;
        "theme/themes/${themeName}/gtk-3.0-settings.ini".text = gtkSettingsIni theme;
        "theme/themes/${themeName}/gtk-4.0-settings.ini".text = gtkSettingsIni theme;
        "theme/themes/${themeName}/gtkrc-2.0".text = gtk2Rc theme;
      }
    )
    { }
    runtimeThemeNames;

  kvantumThemePackage = pkgs.qt6Packages.qtstyleplugin-kvantum;
  runtimeKvantumThemes = lib.unique (map
    (themeName: runtimeThemes.${themeName}.appearance.kvantumTheme)
    runtimeThemeNames);
  extraKvantumThemes = builtins.filter
    (themeName: themeName != config.theme.appearance.kvantumTheme)
    runtimeKvantumThemes;
  kvantumAssets = lib.foldl'
    (acc: themeName:
      acc // {
        "Kvantum/${themeName}".source =
          "${kvantumThemePackage}/share/Kvantum/${themeName}";
      }
    )
    { }
    extraKvantumThemes;

  vscodeSettingsUpdater = pkgs.writeText "theme-switch-vscode-settings.js" ''
    const fs = require("fs");

    const themeSettingsPath = process.argv[2];
    const settingsPath = process.argv[3];

    function stripJsonc(input) {
      let output = "";
      let inString = false;
      let quote = "";
      let escaped = false;
      let inLineComment = false;
      let inBlockComment = false;

      for (let i = 0; i < input.length; i += 1) {
        const ch = input[i];
        const next = input[i + 1];

        if (inLineComment) {
          if (ch === "\n" || ch === "\r") {
            inLineComment = false;
            output += ch;
          }
          continue;
        }

        if (inBlockComment) {
          if (ch === "*" && next === "/") {
            inBlockComment = false;
            i += 1;
          }
          continue;
        }

        if (inString) {
          output += ch;
          if (escaped) {
            escaped = false;
          } else if (ch === "\\") {
            escaped = true;
          } else if (ch === quote) {
            inString = false;
          }
          continue;
        }

        if (ch === "\"" || ch === "'") {
          inString = true;
          quote = ch;
          output += ch;
          continue;
        }

        if (ch === "/" && next === "/") {
          inLineComment = true;
          i += 1;
          continue;
        }

        if (ch === "/" && next === "*") {
          inBlockComment = true;
          i += 1;
          continue;
        }

        output += ch;
      }

      return output;
    }

    function stripTrailingCommas(input) {
      let output = "";
      let inString = false;
      let quote = "";
      let escaped = false;

      for (let i = 0; i < input.length; i += 1) {
        const ch = input[i];

        if (inString) {
          output += ch;
          if (escaped) {
            escaped = false;
          } else if (ch === "\\") {
            escaped = true;
          } else if (ch === quote) {
            inString = false;
          }
          continue;
        }

        if (ch === "\"" || ch === "'") {
          inString = true;
          quote = ch;
          output += ch;
          continue;
        }

        if (ch === ",") {
          let j = i + 1;
          while (j < input.length && /\s/.test(input[j])) {
            j += 1;
          }
          if (input[j] === "}" || input[j] === "]") {
            continue;
          }
        }

        output += ch;
      }

      return output;
    }

    function parseSettings(path) {
      if (!fs.existsSync(path)) {
        return {};
      }

      const text = fs.readFileSync(path, "utf8");
      if (!text.trim()) {
        return {};
      }

      const parsed = JSON.parse(stripTrailingCommas(stripJsonc(text)));
      if (parsed === null || Array.isArray(parsed) || typeof parsed !== "object") {
        throw new Error("VS Code settings must be a JSON object");
      }

      return parsed;
    }

    const nextThemeSettings = JSON.parse(fs.readFileSync(themeSettingsPath, "utf8"));
    const settings = parseSettings(settingsPath);

    for (const [key, value] of Object.entries(nextThemeSettings)) {
      settings[key] = value;
    }

    const tmpPath = settingsPath + ".theme-switch-tmp";
    fs.writeFileSync(tmpPath, JSON.stringify(settings, null, 2) + "\n");
    fs.renameSync(tmpPath, settingsPath);
  '';

  themeSwitch = pkgs.writeShellScriptBin "theme-switch" ''
    set -eu

    DAY_START=7
    DAY_END=18

    usage() {
      printf '%s\n' \
        'Usage:' \
        '  theme-switch auto [--quiet] [--no-reload]' \
        '  theme-switch toggle [--quiet] [--no-reload]' \
        '  theme-switch day|light|night|dark [--quiet] [--no-reload]' \
        '  theme-switch ${lib.concatStringsSep "|" runtimeThemeNames} [--quiet] [--no-reload]' \
        '  theme-switch status'
    }

    quiet=0
    no_reload=0
    command_name=""

    while [ "$#" -gt 0 ]; do
      case "$1" in
        --quiet)
          quiet=1
          ;;
        --no-reload)
          no_reload=1
          ;;
        --help|-h)
          usage
          exit 0
          ;;
        *)
          if [ -n "$command_name" ]; then
            usage >&2
            exit 2
          fi
          command_name="$1"
          ;;
      esac
      shift
    done

    command_name="''${command_name:-auto}"
    config_home="''${XDG_CONFIG_HOME:-$HOME/.config}"
    theme_root="$config_home/theme"
    current_link="$theme_root/current"

    theme_for_time() {
      hour="$(${pkgs.coreutils}/bin/date +%H)"
      hour=$((10#$hour))
      if [ "$hour" -ge "$DAY_START" ] && [ "$hour" -lt "$DAY_END" ]; then
        printf '%s\n' neobrutalist-light
      else
        printf '%s\n' neobrutalist
      fi
    }

    current_theme() {
      if [ -f "$theme_root/current-name" ]; then
        ${pkgs.coreutils}/bin/tr -d '[:space:]' < "$theme_root/current-name"
      elif [ -L "$current_link" ]; then
        ${pkgs.coreutils}/bin/basename "$(${pkgs.coreutils}/bin/readlink "$current_link")"
      else
        theme_for_time
      fi
    }

    case "$command_name" in
      status)
        if [ -L "$current_link" ]; then
          ${pkgs.coreutils}/bin/basename "$(${pkgs.coreutils}/bin/readlink "$current_link")"
        elif [ -f "$theme_root/current-name" ]; then
          ${pkgs.coreutils}/bin/cat "$theme_root/current-name"
        else
          printf '%s\n' none
        fi
        exit 0
        ;;
      auto)
        theme_name="$(theme_for_time)"
        ;;
      toggle)
        case "$(current_theme)" in
          neobrutalist-light)
            theme_name="neobrutalist"
            ;;
          *)
            theme_name="neobrutalist-light"
            ;;
        esac
        ;;
      day|light)
        theme_name="neobrutalist-light"
        ;;
      night|dark)
        theme_name="neobrutalist"
        ;;
      ${lib.concatStringsSep "|" runtimeThemeNames})
        theme_name="$command_name"
        ;;
      *)
        printf 'Unknown theme command: %s\n' "$command_name" >&2
        usage >&2
        exit 2
        ;;
    esac

    theme_dir="$theme_root/themes/$theme_name"
    if [ ! -d "$theme_dir" ]; then
      printf 'Theme assets are missing: %s\n' "$theme_dir" >&2
      exit 1
    fi

    ${pkgs.coreutils}/bin/mkdir -p "$theme_root"
    ${pkgs.coreutils}/bin/ln -sfn "$theme_dir" "$current_link"
    printf '%s\n' "$theme_name" > "$theme_root/current-name"

    link_config() {
      src="$1"
      dest="$2"
      if [ -e "$src" ]; then
        ${pkgs.coreutils}/bin/mkdir -p "$(${pkgs.coreutils}/bin/dirname "$dest")"
        ${pkgs.coreutils}/bin/rm -f "$dest"
        ${pkgs.coreutils}/bin/ln -s "$src" "$dest"
      fi
    }

    link_config "$theme_dir/mako.conf" "$config_home/mako/config"
    link_config "$theme_dir/kvantum.kvconfig" "$config_home/Kvantum/kvantum.kvconfig"
    link_config "$theme_dir/hyprtoolkit.conf" "$config_home/hypr/hyprtoolkit.conf"
    link_config "$theme_dir/btop.theme" "$config_home/btop/themes/current.theme"

    # shellcheck disable=SC1091
    . "$theme_dir/colors.sh"

    update_vscode_settings() {
      settings_file="$config_home/Code/User/settings.json"
      theme_settings="$theme_dir/vscode-settings.json"

      if [ ! -f "$theme_settings" ]; then
        return 0
      fi

      ${pkgs.coreutils}/bin/mkdir -p "$(${pkgs.coreutils}/bin/dirname "$settings_file")"

      if ! ${pkgs.nodejs-slim_22}/bin/node ${vscodeSettingsUpdater} "$theme_settings" "$settings_file"
      then
        printf 'Warning: VS Code settings were not updated\n' >&2
      fi
    }

    update_vscode_settings

    ${pkgs.glib}/bin/gsettings set org.gnome.desktop.interface color-scheme "$GTK_COLOR_SCHEME" >/dev/null 2>&1 || true
    ${pkgs.glib}/bin/gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME" >/dev/null 2>&1 || true
    ${pkgs.glib}/bin/gsettings set org.gnome.desktop.interface icon-theme "$ICON_THEME" >/dev/null 2>&1 || true
    ${pkgs.glib}/bin/gsettings set org.gnome.desktop.interface cursor-theme "$CURSOR_THEME" >/dev/null 2>&1 || true
    ${pkgs.glib}/bin/gsettings set org.gnome.desktop.interface cursor-size "$CURSOR_SIZE" >/dev/null 2>&1 || true

    if [ "$no_reload" -eq 0 ]; then
      ${config.wayland.windowManager.hyprland.package}/bin/hyprctl reload >/dev/null 2>&1 || true
      # The reload re-executes the Lua config and resets every runtime
      # hl.config override; re-apply the active perf mode from its state file.
      ${hyprScripts.perf-mode-auto}/bin/perf-mode-auto >/dev/null 2>&1 || true
      # A USR2 sent before waybar installs its reload handler kills it
      # (Type=simple: active at exec, handler comes later). If waybar became
      # active <10s ago, wait 2s so the handler exists; do not skip the
      # signal, a freshly started bar may have read the old theme symlinks
      # an instant before the relink above.
      waybar_enter_us=$(${pkgs.systemd}/bin/systemctl --user show waybar.service --property ActiveEnterTimestampMonotonic --value 2>/dev/null || echo 0)
      read -r uptime_s _ < /proc/uptime
      if [ "''${waybar_enter_us:-0}" -gt 0 ] 2>/dev/null && \
         [ $(( ''${uptime_s%.*} * 1000000 - waybar_enter_us )) -lt 10000000 ]; then
        ${pkgs.coreutils}/bin/sleep 2
      fi
      ${pkgs.procps}/bin/pkill -SIGUSR2 waybar >/dev/null 2>&1 || true
      ${pkgs.mako}/bin/makoctl reload >/dev/null 2>&1 || \
        ${pkgs.systemd}/bin/systemctl --user restart mako.service >/dev/null 2>&1 || true
      ${pkgs.systemd}/bin/systemctl --user restart swayosd.service >/dev/null 2>&1 || true
      ${pkgs.alacritty}/bin/alacritty msg config -w -1 \
        "colors.primary.background=\"$C_TERM_BG\"" \
        "colors.primary.foreground=\"$C_FG\"" \
        "colors.cursor.text=\"$C_TERM_BG\"" \
        "colors.cursor.cursor=\"$C_ACCENT\"" \
        "colors.selection.text=\"$C_FG\"" \
        "colors.selection.background=\"$C_TERM_SELECTION\"" \
        "colors.normal.black=\"$C_BRIGHT_BLACK\"" \
        "colors.normal.red=\"$C_RED\"" \
        "colors.normal.green=\"$C_GREEN\"" \
        "colors.normal.yellow=\"$C_YELLOW\"" \
        "colors.normal.blue=\"$C_BLUE\"" \
        "colors.normal.magenta=\"$C_MAGENTA\"" \
        "colors.normal.cyan=\"$C_CYAN\"" \
        "colors.normal.white=\"$C_FG\"" \
        "colors.bright.black=\"$C_MUTED\"" \
        "colors.bright.red=\"$C_RED\"" \
        "colors.bright.green=\"$C_GREEN\"" \
        "colors.bright.yellow=\"$C_YELLOW\"" \
        "colors.bright.blue=\"$C_BLUE\"" \
        "colors.bright.magenta=\"$C_MAGENTA\"" \
        "colors.bright.cyan=\"$C_CYAN\"" \
        "colors.bright.white=\"$C_BRIGHT_WHITE\"" >/dev/null 2>&1 || true
    fi

    if [ "$quiet" -eq 0 ]; then
      ${pkgs.libnotify}/bin/notify-send "Theme" "$THEME_DISPLAY_NAME ($theme_name)" >/dev/null 2>&1 || true
      printf 'Theme switched to %s (%s)\n' "$THEME_DISPLAY_NAME" "$theme_name"
    fi
  '';
in
{
  xdg.configFile = themeAssets // kvantumAssets;

  home.packages = [
    themeSwitch
  ];

  home.activation.runtimeThemeInitialLink =
    config.lib.dag.entryAfter [ "writeBoundary" ] ''
      ${themeSwitch}/bin/theme-switch ${initialThemeCommand} --quiet --no-reload || true
    '';

  systemd.user.services.runtime-theme-sync = {
    Unit = {
      Description = "Apply runtime desktop theme for the current time";
      PartOf = [ "graphical-session.target" ];
      After = [ "graphical-session.target" ];
    };
    Service = {
      Type = "oneshot";
      ExecStart = "${themeSwitch}/bin/theme-switch ${initialThemeCommand} --quiet";
    };
    Install.WantedBy = [ "graphical-session.target" ];
  };

  systemd.user.services.runtime-theme-day = {
    Unit.Description = "Switch to the daylight runtime desktop theme";
    Service = {
      Type = "oneshot";
      ExecStart = "${themeSwitch}/bin/theme-switch day --quiet";
    };
  };

  systemd.user.services.runtime-theme-night = {
    Unit.Description = "Switch to the night runtime desktop theme";
    Service = {
      Type = "oneshot";
      ExecStart = "${themeSwitch}/bin/theme-switch night --quiet";
    };
  };

  systemd.user.timers.runtime-theme-day = lib.mkIf scheduledThemeEnabled {
    Unit.Description = "Switch to the daylight runtime desktop theme at 07:00";
    Timer = {
      OnCalendar = "*-*-* 07:00:00";
      Persistent = true;
      Unit = "runtime-theme-day.service";
    };
    Install.WantedBy = [ "timers.target" ];
  };

  systemd.user.timers.runtime-theme-night = lib.mkIf scheduledThemeEnabled {
    Unit.Description = "Switch to the night runtime desktop theme at 18:00";
    Timer = {
      OnCalendar = "*-*-* 18:00:00";
      Persistent = true;
      Unit = "runtime-theme-night.service";
    };
    Install.WantedBy = [ "timers.target" ];
  };
}
