# Automatic DNS switching for VPN and captive portal detection
# When VPN is active: Use VPN DNS (Proton)
# When VPN is inactive: Use dnscrypt-proxy (AdGuard/Mullvad)
# When captive portal detected: Temporarily use network DNS for portal login
{ config, pkgs, ... }:

let
  # Captive portal bypass script (usable manually via sudo)
  captive-portal-bypass = pkgs.writeShellScriptBin "captive-portal-bypass" ''
    # Temporarily bypass dnscrypt-proxy to allow captive portal login
    # Usage: sudo captive-portal-bypass on|off

    PATH=${pkgs.networkmanager}/bin:${pkgs.systemd}/bin:${pkgs.coreutils}/bin:${pkgs.gnugrep}/bin:${pkgs.gnused}/bin:${pkgs.util-linux}/bin:$PATH
    LOCK_FILE="/run/vpn-dns-switch.lock"
    exec 9>"$LOCK_FILE"
    if ! flock -w 10 9; then
      echo "Could not acquire DNS switch lock" >&2
      exit 1
    fi

    write_resolv() {
      local tmpfile
      tmpfile=$(mktemp /etc/resolv.conf.XXXXXX)
      cat > "$tmpfile"
      chmod 644 "$tmpfile"
      mv "$tmpfile" /etc/resolv.conf
    }

    case "''${1:-}" in
      on)
        # Get DNS from the active WiFi connection
        WIFI_IF=$(nmcli -t -f DEVICE,TYPE dev | ${pkgs.gnugrep}/bin/grep ':wifi$' | head -1 | cut -d: -f1)
        if [ -z "$WIFI_IF" ]; then
          echo "No active WiFi interface found"
          exit 1
        fi

        NETWORK_DNS=$(nmcli -t -f IP4.DNS dev show "$WIFI_IF" 2>/dev/null | cut -d: -f2 | tr '\n' ' ' | sed 's/ $//')
        GATEWAY=$(nmcli -t -f IP4.GATEWAY dev show "$WIFI_IF" 2>/dev/null | cut -d: -f2)

        # Use network DNS, or gateway as fallback
        if [ -z "$NETWORK_DNS" ]; then
          NETWORK_DNS="$GATEWAY"
        fi

        if [ -z "$NETWORK_DNS" ]; then
          echo "Could not determine network DNS"
          exit 1
        fi

        systemctl stop dnscrypt-proxy.service
        {
          echo "# Captive portal bypass (managed by VPN-DNS-SWITCH)"
          for dns in $NETWORK_DNS; do
            echo "nameserver $dns"
          done
        } | write_resolv

        touch /tmp/.captive-portal-bypass
        logger "VPN-DNS-SWITCH: Captive portal bypass ON - using network DNS: $NETWORK_DNS"
        echo "Captive portal bypass ON (DNS: $NETWORK_DNS)"
        echo "Run 'sudo captive-portal-bypass off' after logging in to the portal"
        ;;

      off)
        rm -f /tmp/.captive-portal-bypass
        printf '%s\n' "# Generated by VPN-DNS-SWITCH" "nameserver 127.0.0.1" "nameserver ::1" "options edns0" | write_resolv
        systemctl start dnscrypt-proxy.service
        logger "VPN-DNS-SWITCH: Captive portal bypass OFF - restored dnscrypt-proxy"
        echo "Captive portal bypass OFF (dnscrypt-proxy restored)"
        ;;

      *)
        echo "Usage: sudo captive-portal-bypass on|off"
        exit 1
        ;;
    esac
  '';
in
{
  # Make captive-portal-bypass available system-wide
  environment.systemPackages = [ captive-portal-bypass ];

  # Allow marcelo to run captive-portal-bypass without password
  security.sudo.extraRules = [
    {
      users = [ "marcelo" ];
      commands = [
        { command = "${captive-portal-bypass}/bin/captive-portal-bypass"; options = [ "NOPASSWD" ]; }
      ];
    }
  ];

  # NetworkManager dispatcher script for automatic DNS switching
  networking.networkmanager.dispatcherScripts = [
    {
      source = pkgs.writeShellScript "99-vpn-dns-switch" ''
        # NetworkManager dispatcher script
        # $1 = interface name
        # $2 = action (up, down, connectivity-change, vpn-up, vpn-down)

        PATH=${pkgs.networkmanager}/bin:${pkgs.systemd}/bin:${pkgs.openresolv}/bin:${pkgs.coreutils}/bin:${pkgs.gnugrep}/bin:${pkgs.gnused}/bin:${pkgs.procps}/bin:${pkgs.util-linux}/bin:${pkgs.curl}/bin:$PATH
        LOCK_FILE="/run/vpn-dns-switch.lock"
        exec 9>"$LOCK_FILE"
        if ! flock -w 10 9; then
          logger "VPN-DNS-SWITCH: skipped $2 on $1 because lock was busy"
          exit 0
        fi

        # Atomic write helper: writes to temp file then moves (prevents truncated resolv.conf)
        write_resolv() {
          local tmpfile
          tmpfile=$(mktemp /etc/resolv.conf.XXXXXX)
          cat > "$tmpfile"
          chmod 644 "$tmpfile"
          mv "$tmpfile" /etc/resolv.conf
        }

        restore_secure_dns() {
          rm -f /tmp/.captive-portal-bypass
          printf '%s\n' "# Generated by VPN-DNS-SWITCH" "nameserver 127.0.0.1" "nameserver ::1" "options edns0" | write_resolv
          systemctl start dnscrypt-proxy.service
        }

        # Captive portal detection: temporarily use network DNS to check connectivity
        # Returns 0 (true) if a captive portal IS detected
        # Uses atomic writes to prevent truncated resolv.conf if process is killed
        check_captive_portal() {
          local WIFI_IF="$1"
          local NETWORK_DNS=$(nmcli -t -f IP4.DNS dev show "$WIFI_IF" 2>/dev/null | cut -d: -f2 | head -1)
          local GATEWAY=$(nmcli -t -f IP4.GATEWAY dev show "$WIFI_IF" 2>/dev/null | cut -d: -f2)

          local CHECK_DNS="''${NETWORK_DNS:-$GATEWAY}"
          [ -z "$CHECK_DNS" ] && return 1

          # Save current resolv.conf and set trap to restore it atomically
          local ORIG_RESOLV
          ORIG_RESOLV=$(cat /etc/resolv.conf)
          trap 'printf "%s\n" "$ORIG_RESOLV" | write_resolv' EXIT INT TERM HUP

          # Temporarily write network DNS to resolv.conf for the check (atomic)
          printf '%s\n' "# Temporary captive portal check" "nameserver $CHECK_DNS" | write_resolv

          # Match NetworkManager's expected response body. Captive portals often
          # return their login page with HTTP 200, so the status code is not enough.
          local RESPONSE=""
          local ATTEMPT
          for ATTEMPT in 1 2 3; do
            RESPONSE=$(curl -sS --max-time 5 "http://nmcheck.gnome.org/check_network_status.txt" 2>/dev/null || true)
            if [ "$RESPONSE" = "NetworkManager is online" ]; then
              break
            fi
            [ -n "$RESPONSE" ] && break
            sleep 2
          done

          # Restore original resolv.conf atomically (also handled by trap)
          printf '%s\n' "$ORIG_RESOLV" | write_resolv
          trap - EXIT INT TERM HUP

          # Anything except the exact success body is limited connectivity. Fail
          # open to network DNS so slow airport WiFi can still expose its portal.
          [ "$RESPONSE" != "NetworkManager is online" ]
        }

        INTERFACE="$1"
        ACTION="$2"

        # WireGuard is not treated as a VPN by NetworkManager, so we detect it by interface name
        case "$ACTION" in
          up)
            # Check if this is a Proton VPN (WireGuard) interface
            if [[ "$INTERFACE" == "proton"* ]]; then
              # ProtonVPN WireGuard is now active - get VPN DNS and configure it
              logger "VPN-DNS-SWITCH: Proton VPN activated on $INTERFACE - switching to VPN DNS"

              # Get DNS servers from the VPN connection
              VPN_DNS=$(nmcli -t -f IP4.DNS dev show "$INTERFACE" 2>/dev/null | cut -d: -f2 | tr '\n' ' ' | sed 's/ $//')

              if [ -n "$VPN_DNS" ]; then
                # Stop dnscrypt-proxy
                systemctl stop dnscrypt-proxy.service

                # Configure VPN DNS in resolv.conf (atomic write)
                {
                  echo "# VPN DNS (managed by VPN-DNS-SWITCH)"
                  for dns in $VPN_DNS; do
                    echo "nameserver $dns"
                  done
                } | write_resolv

                logger "VPN-DNS-SWITCH: Configured VPN DNS: $VPN_DNS"

                # Notify Waybar - multiple methods for reliability
                # Method 1: Direct pkill as user (most reliable)
                su - marcelo -c 'pkill -RTMIN+8 waybar' 2>/dev/null || true
                # Method 2: Systemd user service as fallback
                systemctl --machine=marcelo@.host --user start waybar-vpn-refresh.service 2>/dev/null || true
              else
                logger "VPN-DNS-SWITCH: WARNING - No DNS from VPN, keeping dnscrypt-proxy active"
              fi
            else
              # Regular connection up - ensure DNS is working if no VPN active
              VPN_ACTIVE=$(nmcli -t -f DEVICE connection show --active | grep -E "^proton" || true)
              if [ -z "$VPN_ACTIVE" ]; then
                DEVICE_TYPE=$(nmcli -t -f DEVICE,TYPE dev | grep "^$INTERFACE:" | cut -d: -f2)

                if [ "$DEVICE_TYPE" = "wifi" ]; then
                  # WiFi: check for captive portal BEFORE starting dnscrypt-proxy
                  # dnscrypt-proxy can't resolve anything behind a captive portal
                  sleep 2  # Give the connection a moment to fully establish

                  # Stop dnscrypt-proxy during the check so it doesn't interfere
                  systemctl stop dnscrypt-proxy.service 2>/dev/null || true

                  if check_captive_portal "$INTERFACE"; then
                    logger "VPN-DNS-SWITCH: Captive portal detected on $INTERFACE - using network DNS"

                    NETWORK_DNS=$(nmcli -t -f IP4.DNS dev show "$INTERFACE" 2>/dev/null | cut -d: -f2 | tr '\n' ' ' | sed 's/ $//')
                    GATEWAY=$(nmcli -t -f IP4.GATEWAY dev show "$INTERFACE" 2>/dev/null | cut -d: -f2)
                    PORTAL_DNS="''${NETWORK_DNS:-$GATEWAY}"

                    {
                      echo "# Captive portal bypass (managed by VPN-DNS-SWITCH)"
                      for dns in $PORTAL_DNS; do
                        echo "nameserver $dns"
                      done
                    } | write_resolv

                    touch /tmp/.captive-portal-bypass
                    logger "VPN-DNS-SWITCH: Using network DNS for captive portal: $PORTAL_DNS"

                    # Notify user
                    su - marcelo -c "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u marcelo)/bus notify-send -u critical 'Captive Portal Detected' 'Network DNS enabled for login; secure DNS will be restored automatically'" 2>/dev/null || true
                  else
                    # No captive portal - safe to use dnscrypt-proxy
                    logger "VPN-DNS-SWITCH: No captive portal on $INTERFACE - starting dnscrypt-proxy"
                    restore_secure_dns
                  fi
                else
                  # Non-WiFi (ethernet etc): start dnscrypt-proxy directly (no captive portals)
                  if ! systemctl is-active --quiet dnscrypt-proxy.service; then
                    logger "VPN-DNS-SWITCH: No VPN active - ensuring dnscrypt-proxy is running"
                    systemctl start dnscrypt-proxy.service
                    printf '%s\n' "# Generated by VPN-DNS-SWITCH" "nameserver 127.0.0.1" "nameserver ::1" "options edns0" | write_resolv
                  fi
                fi
              fi
            fi
            ;;

          down)
            # Check if this is a Proton VPN (WireGuard) interface being disconnected
            if [[ "$INTERFACE" == "proton"* ]]; then
              # ProtonVPN WireGuard is now inactive - restart dnscrypt-proxy
              logger "VPN-DNS-SWITCH: Proton VPN deactivated on $INTERFACE - restoring dnscrypt-proxy"

              # Restore localhost DNS (atomic write)
              printf '%s\n' "# Generated by VPN-DNS-SWITCH" "nameserver 127.0.0.1" "nameserver ::1" "options edns0" | write_resolv

              # Start dnscrypt-proxy
              systemctl start dnscrypt-proxy.service

              logger "VPN-DNS-SWITCH: Restored dnscrypt-proxy (127.0.0.1)"

              # Notify Waybar - multiple methods for reliability
              # Method 1: Direct pkill as user (most reliable)
              su - marcelo -c 'pkill -RTMIN+8 waybar' 2>/dev/null || true
              # Method 2: Systemd user service as fallback
              systemctl --machine=marcelo@.host --user start waybar-vpn-refresh.service 2>/dev/null || true
            fi

            # Do not leave network DNS active after leaving a captive WiFi.
            if [ -e /tmp/.captive-portal-bypass ]; then
              logger "VPN-DNS-SWITCH: Captive network disconnected - restoring dnscrypt-proxy"
              restore_secure_dns
            fi
            ;;

          connectivity-change)
            # NetworkManager checks the expected response every 30 seconds. Once
            # portal consent succeeds, restore encrypted DNS without user action.
            if [ "''${CONNECTIVITY_STATE:-}" = "FULL" ] && [ -e /tmp/.captive-portal-bypass ]; then
              logger "VPN-DNS-SWITCH: Captive portal login complete - restoring dnscrypt-proxy"
              restore_secure_dns
              su - marcelo -c "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u marcelo)/bus notify-send 'Secure DNS Restored' 'Captive portal login complete; Mullvad/AdGuard DNS is active again'" 2>/dev/null || true
            fi
            ;;
        esac
      '';
      type = "basic";
    }
  ];
}
