# Hardware configuration for ThinkPad P14s Gen 5 (AMD)
# AMD Ryzen 7 PRO 8840HS + Radeon 780M Graphics
# This file will be replaced by the output of nixos-generate-config during installation
# This is a template with optimized settings for this specific model

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # AMD Ryzen 7 PRO 8840HS - Zen 4 architecture
  # 8 cores, 16 threads, 3.3GHz base, 5.1GHz boost
  boot.initrd.availableKernelModules = [
    "nvme"        # NVMe SSD support
    "xhci_pci"    # USB 3.0 support
    "thunderbolt" # Thunderbolt/USB4 support
    "usb_storage" # USB storage
    "sd_mod"      # SD card reader
    "rtsx_pci_sdmmc" # Realtek card reader
  ];

  boot.initrd.kernelModules = [ "amdgpu" ]; # Load AMD GPU driver early
  boot.kernelModules = [ "kvm-amd" ];       # KVM virtualization
  boot.extraModulePackages = [ ];

  # AMD Radeon 780M iGPU - RDNA 3 architecture
  # Optimized configuration for integrated graphics
  hardware.graphics = {
    enable = true;
    enable32Bit = true; # For 32-bit applications (Steam, Wine, etc.)

    # Mesa drivers with Vulkan support (RADV)
    extraPackages = with pkgs; [
      # AMD ROCm OpenCL runtime (for compute/AI workloads)
      rocmPackages.clr.icd

      # AMDVLK (alternative Vulkan driver - not recommended, causes issues)
      # amdvlk  # Commented: Mesa RADV is preferred
    ];

    # 32-bit support for gaming
    extraPackages32 = with pkgs; [
      driversi686Linux.mesa
    ];
  };

  # AMD GPU drivers (use amdgpu, not radeon legacy driver)
  services.xserver.videoDrivers = [ "amdgpu" ];

  # ROCm configuration consolidated in amd-optimizations.nix
  # systemd.tmpfiles.rules = [
  #   "L+    /opt/rocm/hip   -    -    -     -    ${pkgs.rocmPackages.clr}"
  # ];
  # hardware.graphics.extraPackages consolidated in amd-optimizations.nix

  # Firmware updates
  services.fwupd.enable = true;

  # Filesystems - TEMPLATE (1TB SSD)
  # These will be generated by nixos-generate-config during installation
  # Example structure for 1TB SSD (adjust to your setup):
  #
  # fileSystems."/" = {
  #   device = "/dev/disk/by-uuid/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
  #   fsType = "ext4";  # or "btrfs" for better features
  # };
  #
  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/XXXX-XXXX";
  #   fsType = "vfat";
  # };
  #
  # # Optional: Swap file (recommended 16GB for 1TB SSD)
  # swapDevices = [
  #   { device = "/swapfile"; size = 16384; }
  # ];

  # CPU microcode updates
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Networking hardware
  networking.useDHCP = lib.mkDefault true;

  # Power management (CPU governor handled by TLP in services.nix)
  # powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";  # Removed: TLP manages this

  # Thermald configuration moved to services.nix to avoid duplication
  # services.thermald.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
