# VS Code Latest - Always fetches the latest version from Microsoft
# This file is auto-generated by the update-vscode script
# Run: update-vscode to check for updates and apply them automatically

{ fetchurl, vscode, libxtst, libjpeg8, pipewire, libei, ... }:

let
  # AUTO-UPDATED BY update-vscode SCRIPT
  version = "1.130.0";
  sha256 = "sha256-fWrT06eKxFUcFGMfeNfgPIUoKrUFw86LG8BOAfr+iOo=";
in
vscode.overrideAttrs (oldAttrs: {
  inherit version;

  src = fetchurl {
    url = "https://update.code.visualstudio.com/${version}/linux-x64/stable";
    inherit sha256;
    name = "vscode-${version}.tar.gz";
  };

  # Obsolete: nixpkgs' vscode (1.127.0 in the locked snapshot) already targets
  # @vscode/ripgrep-universal/bin/linux-x64/rg, so this rewrite is the
  # anticipated harmless no-op. Safe to drop together with the postPatch below.
  postPatch = builtins.replaceStrings
    [ "@vscode/ripgrep/bin/rg" ]
    [ "@vscode/ripgrep-universal/bin/linux-x64/rg" ]
    oldAttrs.postPatch;

  buildInputs = (oldAttrs.buildInputs or []) ++ [
    libxtst
    libjpeg8.out
    pipewire
    libei
  ];

  # Ignore missing deps for Microsoft auth extension (optional, browser-based auth)
  # and the musl-libc variant of the Copilot native binary (we use the glibc one).
  autoPatchelfIgnoreMissingDeps = (oldAttrs.autoPatchelfIgnoreMissingDeps or []) ++ [
    "libcurl.so.4"
    "libcrypto.so.3"
    "libwebkit2gtk-4.1.so.0"
    "libsoup-3.0.so.0"
    "libc.musl-x86_64.so.1"
  ];

  meta = oldAttrs.meta // {
    description = "Visual Studio Code - Latest (${version})";
  };
})
