# VS Code Latest - Always fetches the latest version from Microsoft
# This file is auto-generated by the update-vscode script
# Run: update-vscode to check for updates and apply them automatically

{ lib, fetchurl, vscode, ... }:

let
  # AUTO-UPDATED BY update-vscode SCRIPT
  version = "1.107.1";
  sha256 = "sha256-qaGeIN0Jxh7Br31n2d7CRVAE0PvTUSD+HSRYjBI/lHQ=";
in
vscode.overrideAttrs (oldAttrs: {
  inherit version;

  src = fetchurl {
    url = "https://update.code.visualstudio.com/${version}/linux-x64/stable";
    inherit sha256;
    name = "vscode-${version}.tar.gz";
  };

  meta = oldAttrs.meta // {
    description = "Visual Studio Code - Latest (${version})";
  };
})
