# VS Code Latest - Always fetches the latest version from Microsoft
# This file is auto-generated by the update-vscode script
# Run: update-vscode to check for updates and apply them automatically

{ lib, fetchurl, vscode, ... }:

let
  # AUTO-UPDATED BY update-vscode SCRIPT
  version = "1.108.1";
  sha256 = "sha256-qYthiZlioD6fWCyDPfg7Yfo5PqCHzcenk8NjgobLW7c=";
in
vscode.overrideAttrs (oldAttrs: {
  inherit version;

  src = fetchurl {
    url = "https://update.code.visualstudio.com/${version}/linux-x64/stable";
    inherit sha256;
    name = "vscode-${version}.tar.gz";
  };

  # Ignore missing deps for Microsoft auth extension (optional, browser-based auth)
  autoPatchelfIgnoreMissingDeps = (oldAttrs.autoPatchelfIgnoreMissingDeps or []) ++ [
    "libcurl.so.4"
    "libcrypto.so.3"
    "libwebkit2gtk-4.1.so.0"
    "libsoup-3.0.so.0"
  ];

  meta = oldAttrs.meta // {
    description = "Visual Studio Code - Latest (${version})";
  };
})
